### ISSUE TITLE
Can we color the modified buffer?

### ISSUE THREAD

**Issue by twmht** [j-morano/buffer_manager.nvim#17]
When the buffer is modified but not saved yet.  This is usually happen, Can we color the unsaved buffer in the pop-up menu?

**Comment by j-morano** [comment]
Hello. Thanks for the feedback I think it is a good idea. I will work on it as soon as I can.

**Comment by twmht** [comment]
@j-morano 

oh thank you. this would be good.

**Comment by j-morano** [comment]
Hi! I added a commit in the branch [highlight-modified](https://github.com/j-morano/buffer_manager.nvim/tree/highlight-modified) with this feature. In order to work, you have to configure the highlight group `BufferManagerModified` in your config. For example:
```vim
hi BufferManagerModified ctermfg=19 guifg=#0000af
```

I think it works ok, but I would appreciate if you cant test it too before merging it to main. To do it, you just have to change the branch in the plugin manager. For example, in Packer:
```lua
  use { 'j-morano/buffer_manager.nvim', branch = 'highlight-modified' }
```

Thank you in advance!

**Comment by twmht** [comment]
@j-morano 

I tested that, it works

![image](https://user-images.githubusercontent.com/1567200/227718357-1b86fea9-fec3-4cd1-b9df-6d3b598a9de2.png)

**Comment by j-morano** [comment]
Thank you for the feedback. I think it is a good idea. I will merge the branch with the `main` branch today.
