### ISSUE TITLE
[feature request] Sync buffer_manager.nvim with bufferline.nvim

### ISSUE THREAD

**Issue by haru02w** [j-morano/buffer_manager.nvim#21]
Would be really cool to sync the ordering of buffers between these two plugins.

**Comment by j-morano** [comment]
Hello. Thanks for the idea. I personally am not interested, as I don't use that plugin. However, since `bufferline.nvim` is a popular plugin, I will look at its code to see how complicated it is to implement.

Whether it is possible or not will depend on where the plugin stores the buffers. If that information is accessible from external code, it could be done. In principle, it seems so ([bufferline/commands.lua](https://github.com/akinsho/bufferline.nvim/blob/main/lua/bufferline/commands.lua)). When I have more time I will look at it in more detail.

**Comment by j-morano** [comment]
Hello again. I had time to look at the implementation of `bufferline.nvim`, and I was wrong. It is not possible to access that data from another plugin. Therefore, I cannot implement this feature. Sorry. I will close the issue as not planed.
Thanks anyway for the feedback, and please feel free to open other issue if you have any other feature requests. Regards!

**Comment by accrrsd** [comment]
What about lualine? It allows you to display custom information in its fields and also has a building to display buffers, which of course differ in order from buffers in this plugin. It would be great if you would take a look towards lualine support!

[Lualine buffers display code](https://github.com/nvim-lualine/lualine.nvim/tree/master/lua/lualine/components/buffers)
