### ISSUE TITLE
nav_prev, nav_next functions bug

### ISSUE THREAD

**Issue by gonviegas** [j-morano/buffer_manager.nvim#8]
Sometimes, after opening buffers with nvim-tree/nvim-tree.lua, the buffers aren't found when trying to cycle them through nav_prev and nav_next functions but it is fixed after running the toggle_quick_menu() function. 

Also, after deleting a buffer with famiu/bufdelete.nvim, when cycling the buffers with nav_prev and nav_next functions, the previous deleted buffer appears again, but it is fixed if toggle_quick_menu() is used after deleting the buffer. 

Seems like something should be done in the cycling functions to refresh the buffer-manager buffer list...

**Comment by j-morano** [comment]
Yes, you are right. Probably, we need to add some calls to the function `initialize_marks()`, from `ui.lua`. I will work on it as soon as I can. And thanks for the feedback!

**Comment by gonviegas** [comment]
In the meantime, I've mapped 2x toggle_quick_menu() to run before nav_prev, nav_next or bufdelete and it works flawlessly. 

You're welcome and thank you for this plugin, as it is exactly what I needed.

**Comment by j-morano** [comment]
Hello. I have added a commit (4a21ea5) that I think it solves the issue. However, I would appreciate it if you could test it too, to check that everything is working properly.
This issue is linked to the branch [automatic-marks-update](https://github.com/j-morano/buffer_manager.nvim/tree/automatic-marks-update), so it is the commit 4a21ea5. Thus, to test it, you have to add the branch information to Packer (or whatever plugin manager you use). Here is an example for Packer:
```lua
  use { 'j-morano/buffer_manager.nvim', branch = 'automatic-marks-update' }
```
Let me know if there are any bugs.

**Comment by j-morano** [comment]
Hello. I have added a commit ([396cf71](https://github.com/j-morano/buffer_manager.nvim/commit/396cf71682e26d49ae37c73f2b375d3a223eea2f)) that I think it solves the issue (the previous one, [4a21ea5](https://github.com/j-morano/buffer_manager.nvim/commit/4a21ea5d3a2fe8d672f0b41291f5e322138d27fb), was wrong). However, I would appreciate it if you could test it too, to check that everything is working properly.
This issue is linked to the branch [update-marks](https://github.com/j-morano/buffer_manager.nvim/tree/update-marks), and so it is the commit [396cf71](https://github.com/j-morano/buffer_manager.nvim/commit/396cf71682e26d49ae37c73f2b375d3a223eea2f). Thus, to test it, you have to add the branch information to Packer (or whatever plugin manager you use). Here is an example for Packer:
```lua
use { 'j-morano/buffer_manager.nvim', branch = 'update-marks' }
```
Let me know if there are any bugs.

**Comment by j-morano** [comment]
Hi. Nice to hear that it works in most cases.
Regarding your specific issue, I am not sure I can solve it. The plugin already checks if the name of the buffer is empty and if it is listed. Is `bufdelete.nvim` correctly removing the empty buffer after it is replaced? In those cases, which is the output of the command `:ls`?

**Comment by j-morano** [comment]
I merged the branch, but I have reopened the issue until I know the source of the specific issue that you have.

**Comment by gonviegas** [comment]
You're right, the empty buffer is still there. I actually don't know if this should be solved by buffer_manager or not... What I know is that using bufferline this didn't happen but I don't know if they would close it or simply bypass it.

**Comment by j-morano** [comment]
Thank you for taking the time of reporting the issue. I appreciate the feedback.
And I'm fine with that matter being another issue. Feel free to open it; we can work on it.
